const express = require('express');
const { body } = require('express-validator');
const { register, login, profile } = require('../controllers/authController');
const auth = require('../middleware/auth');
const router = express.Router();
const credentials = [body('email').isEmail(), body('password').isLength({ min: 6 })];
router.post('/register', [body('name').trim().notEmpty(), ...credentials], register);
router.post('/login', credentials, login);
router.get('/profile', auth, profile);
module.exports = router;
