const express = require('express');
const { create, list, getOne, update, remove } = require('../controllers/blogController');
const auth = require('../middleware/auth');
const router = express.Router();
router.post('/', auth, create);
router.get('/', list);
router.get('/:id', getOne);
router.put('/:id', auth, update);
router.delete('/:id', auth, remove);
module.exports = router;
